apiVersion: v1
kind: ConfigMap
metadata:
  name: nativelink-config-cas
  labels:
    {{- include "nativelink-applovin.labels" . | nindent 4 }}
    component: local_storage_cas
data:
  conf.json5: |-
    {{ .Values.local_storage_cas.conf | nindent 4 }}

