apiVersion: v1
kind: Service
metadata:
  name: nativelink-cas
  labels:
    {{- include "nativelink-applovin.labels" . | nindent 4 }}
    component: local_storage_cas
  {{- with .Values.local_storage_cas.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.local_storage_cas.service.type }}
  ports:
    {{- toYaml .Values.local_storage_cas.service.ports | nindent 4 }}
  selector:
    {{- include "nativelink-applovin.selectorLabels" . | nindent 4 }}
    component: local_storage_cas
---
apiVersion: v1
kind: Service
metadata:
  name: nativelink-scheduler
  labels:
    {{- include "nativelink-applovin.labels" . | nindent 4 }}
    component: scheduler
  {{- with .Values.scheduler.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
    {{- toYaml .Values.scheduler.service.ports | nindent 4 }}
  selector:
    {{- include "nativelink-applovin.selectorLabels" . | nindent 4 }}
    component: scheduler

