apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nativelink-worker
  labels:
    {{- include "nativelink-applovin.labels" . | nindent 4 }}
    component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  serviceName: nativelink-worker
  selector:
    matchLabels:
      {{- include "nativelink-applovin.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap_worker.yaml") . | sha256sum }}
      {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nativelink-applovin.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nativelink-applovin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: nativelink
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          {{- with .Values.worker.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "/conf.json5"
        {{- with .Values.worker.containerPorts }}
          ports:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.worker.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.worker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.worker.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.worker.persistence.enabled }}
            - name: nativelink-worker
              mountPath: /root/.cache/nativelink/
            {{- end }}
            - name: nativelink-config
              mountPath: /conf.json5
              subPath: conf.json5
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nativelink-config
          configMap:
            name: nativelink-config-worker
  {{- if .Values.worker.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: nativelink-worker
      spec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: {{ .Values.worker.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.worker.persistence.size }}
  {{- end }}